forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/stdlib', '4.25.1'
mod 'puppetlabs/apt', '2.4.0'
mod 'puppetlabs/ntp', '4.2.0'
mod 'puppetlabs/vcsrepo', '1.5.0'
mod 'puppetlabs/postgresql', '4.9.0'
mod 'puppet/collectd', '4.3.0' # 5.3.0
mod 'puppet/nginx', '0.4.0' # 0.5.0
mod 'puppet/unattended_upgrades', '1.1.1' #2.2.0

mod 'nginx',
  :git => 'https://github.com/voxpupuli/puppet-nginx.git',
  :ref => 'b58a3f4e0cd3888f63f9db0b2f5a33988cd538ca'
mod 'rrdcached',
  :git => 'https://github.com/freifunk-berlin/puppet-rrdcached.git'
mod 'boo-php-fpm',
  :git => 'https://github.com/rtznprmpftl/puppet-php-fpm.git',
  :ref => 'puppet5_compat'
mod 'sysctl',
  :git => 'https://github.com/thias/puppet-sysctl'
mod 'files',
  :git => 'https://github.com/freifunk-berlin/puppet-files'
mod 'vpn03',
  :git => 'https://github.com/freifunk-berlin/puppet-vpn03'
mod 'tunneldigger',
  :git => 'https://github.com/freifunk-berlin/puppet-tunneldigger'
mod 'communitytunnel',
  :git => 'https://github.com/freifunk-berlin/puppet-communitytunnel'
mod 'bbbdigger',
  :git => 'https://github.com/freifunk-berlin/puppet-bbbdigger'
mod 'uwsgi',
  :git => 'https://github.com/Engage/puppet-uwsgi'
mod 'python',
  :git => 'https://github.com/stankevich/puppet-python'
mod 'exim4',
  :git => 'https://github.com/ULHPC/puppet-exim4',
  :ref => 'production'

