forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'puppetlabs/ntp'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/postgresql'

mod 'nginx',
  :git => 'https://github.com/jfryman/puppet-nginx.git'
mod 'collectd',
  :git => 'https://github.com/puppet-community/puppet-collectd'
mod 'rrdcached',
  :git => 'https://github.com/booo/puppet-rrdcached.git'
mod 'php-fpm',
  :git => 'https://github.com/booo/puppet-php-fpm.git'
mod 'sysctl',
  :git => 'https://github.com/thias/puppet-sysctl'
mod 'files',
  :git => 'https://github.com/freifunk/berlin-puppet-files'
mod 'vpn03',
  :git => 'https://github.com/freifunk-berlin/puppet-vpn03'
mod 'tunneldigger'
  :git => 'https://github.com/freifunk-berlin/puppet-tunneldigger'
mod 'community-tunneldigger'
  :git => 'https://github.com/freifunk-berlin/puppet-community-tunneldigger'
mod 'uwsgi',
  :git => 'https://github.com/Engage/puppet-uwsgi'
mod 'python',
  :git => 'https://github.com/stankevich/puppet-python'
mod 'unattended_upgrades',
  :git => 'https://github.com/puppet-community/puppet-unattended_upgrades'
mod 'exim4',
  :git => 'https://github.com/ULHPC/puppet-exim4',
  :ref => 'production'

