# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.



  config.vm.box = "ubuntu/bionic64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.

  # TODO: move forwarded ports to the machine definition so you can run multiple at a time
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 443, host: 8443

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  #config.vm.network :public_network

  config.vm.define "config" do |web|
    hostname = "config.berlin.freifunk.net"
    web.vm.host_name = hostname
    web.vm.provision "shell", path: "./scripts/ssl.sh", args: hostname

    web.vm.provision "shell",
      inline: "apt-get update; apt-get install -y puppet "

    web.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "site.pp"
      puppet.module_path = "modules"
    end
  end

  config.vm.define "buildbot" do |buildbot|
    hostname = "buildbot.berlin.freifunk.net"
    buildbot.vm.host_name = hostname
    buildbot.vm.box = "debian/contrib-buster64"

    buildbot.vm.provision "shell", path: "./scripts/ssl.sh", args: hostname

    buildbot.vm.provision "shell",
      inline: "apt-get update; apt-get install -y puppet "

    buildbot.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "site.pp"
      puppet.module_path = "modules"
    end
  end



  config.vm.define "monitor" do |monitor|
    hostname = "monitor.berlin.freifunk.net"
    monitor.vm.host_name = hostname
    monitor.vm.provision "shell", path: "./scripts/ssl.sh", args: hostname

    monitor.vm.provision "shell",
      inline: "apt-get update; apt-get install -y puppet "

    monitor.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "site.pp"
      puppet.module_path = "modules"
    end
  end



  config.vm.define "vpn03" do |vpn03|
    hostname = "vpn03a.berlin.freifunk.net"
    vpn03.vm.host_name = hostname
    # the vpn03 module depends on packages only available for older OS releases
    vpn03.vm.box = "ubuntu/xenial64"

    vpn03.vm.provision "shell",
      inline: "apt-get update; apt-get install -y puppet "

    vpn03.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "site.pp"
      puppet.module_path = "modules"
    end
  end

  config.vm.define "bbbvpn" do |bbbvpn|
    # the bbbvpn module depends on packages only available for debian jessie and stretch
    bbbvpn.vm.box = "debian/contrib-stretch64"
    hostname = "l105-bbbvpn.berlin.freifunk.net"
    bbbvpn.vm.host_name = hostname

    bbbvpn.vm.provision "shell",
      inline: "apt-get update; apt-get install -y puppet "

    bbbvpn.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "site.pp"
      puppet.module_path = "modules"
    end
  end

  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    #vb.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end
end
